CREATE TABLE IF NOT EXISTS bus_traffic_processed (
    RecordedAtTime_year INTEGER,
    RecordedAtTime_month INTEGER,
    RecordedAtTime_day INTEGER,
    RecordedAtTime_hour INTEGER,
    RecordedAtTime_minute INTEGER,
    RecordedAtTime_second INTEGER,
    ExpectedArrivalTime_year INTEGER,
    ExpectedArrivalTime_month INTEGER,
    ExpectedArrivalTime_day INTEGER,
    ExpectedArrivalTime_hour INTEGER,
    ExpectedArrivalTime_minute INTEGER,
    ExpectedArrivalTime_second INTEGER,
    ScheduledArrivalTime_hour INTEGER,
    ScheduledArrivalTime_minute INTEGER,
    ScheduledArrivalTime_second INTEGER,
    DirectionRef INTEGER,
    PublishedLineName VARCHAR(255),
    OriginName VARCHAR(255),
    OriginCoordinates DOUBLE PRECISION,
    DestinationName VARCHAR(255),
    DestinationCoordinates DOUBLE PRECISION,
    VehicleRef VARCHAR(255),
    VehicleCoordinates DOUBLE PRECISION,
    NextStopPointName VARCHAR(255),
    ArrivalProximityText VARCHAR(255),
    DistanceFromStop DOUBLE PRECISION,
    Delay DOUBLE PRECISION,
    PRIMARY KEY (RecordedAtTime_year, RecordedAtTime_month, RecordedAtTime_day, RecordedAtTime_hour, RecordedAtTime_minute, RecordedAtTime_second)
);

